knights_list = ["Sir Lancelot","Sir Galahad","Sir Gawain","Sir Perceval","Sir Tristram","Sir Gareth"]
print("Knights list = ",knights_list)
print()
print()
knights_list.append("Sir Kay")
print("After 'Sir Kay' was appended Knights list is now:")
print()
print(knights_list)
print()
print()
knights_list.sort()
print("After sorting into alphabetical order knights_list is now:")
print()
print (knights_list)
print()
print()
print("knights_list[0] =", knights_list[0])
print("knights_list[1] =", knights_list[1])
print()
print()
del knights_list[3]
print("After 'del knights_list[3]',  knights_list is now:")
print()
print (knights_list)
